name: Deploy to Firebase on merge
on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # ────────────────────────────────────────────
            # ２つのサービスアカウント JSON を Secrets から書き出し
            - name: Write Firebase Service Accounts
              env:
                  PT_ADMIN_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PT_ADMIN_4D877 }}
                  PAWTICKET_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAWTICKET_APP_6B651 }}
              run: |
                  mkdir -p firebase-admin
                  echo "$PT_ADMIN_JSON"   > firebase-admin/pt-admin-firebase.json
                  echo "$PAWTICKET_JSON"  > firebase-admin/pawticket-app-firebase.json
                  chmod 600 firebase-admin/*.json
            # ────────────────────────────────────────────
            - run: yarn install --frozen-lockfile && yarn build

            # ────────────────────────────────────────────
            # Hosting と Functions をまとめてデプロイ（公式CLIアクション）
            # Hosting
            - name: Deploy Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PT_ADMIN_4D877 }}
                  projectId: pt-admin-4d877
                  channelId: live

            # Functions
            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Install Functions dependencies
              working-directory: functions
              run: cd functions && yarn install --frozen-lockfile

            - name: Deploy Functions
              env:
                  # サービスアカウント JSON を指して CLI 認証させる
                  GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-admin/pt-admin-firebase.json
              run: |
                  npx firebase deploy --only functions --project pt-admin-4d877
            # ────────────────────────────────────────────
