name: Deploy to Firebase Hosting on merge
on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # ────────────────────────────────────────────
            # ２つのサービスアカウント JSON を Secrets から書き出し
            - name: Write Firebase Service Accounts
              env:
                  PT_ADMIN_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PT_ADMIN_4D877 }}
                  PAWTICKET_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PAWTICKET_APP_6B651 }}
              run: |
                  mkdir -p firebase-admin
                  # 管理画面用
                  echo "$PT_ADMIN_JSON" > firebase-admin/pt-admin-firebase.json
                  # アプリ用
                  echo "$PAWTICKET_JSON" > firebase-admin/pawticket-app-firebase.json
                  chmod 600 firebase-admin/*.json
            # ────────────────────────────────────────────
            - run: yarn install --frozen-lockfile && yarn build

            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PT_ADMIN_4D877 }}
                  channelId: live
                  projectId: pt-admin-4d877
