name: Deploy to Firebase on merge
on:
    push:
        branches: [main]

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write # ← auth@v2 に必要

        steps:
            - uses: actions/checkout@v4

            - name: Use Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "yarn"

            # ルートの依存＆Next.jsビルド
            - run: yarn install --frozen-lockfile
            - run: yarn build
              env:
                  NEXT_TELEMETRY_DISABLED: "1"

            # Firebase CLI
            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            # GCP認証（サービスアカウントJSONを使う場合）
            # Workload Identity を使うなら workload_identity_provider / service_account を使う書式に変更
            - name: Authenticate to Google Cloud
              id: auth
              uses: google-github-actions/auth@v2
              with:
                  credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PT_ADMIN_4D877 }}

            # Firebase CLI が ADC を拾えるように環境変数をセット
            - name: Export ADC path for Firebase CLI
              run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ steps.auth.outputs.credentials_file_path }}" >> $GITHUB_ENV

            # Functions 依存＆ビルド
            - name: Install Functions dependencies
              working-directory: functions
              run: yarn install --frozen-lockfile

            # Deploy Functions (Gen2)
            - name: Deploy Functions (Gen2)
              run: |
                  firebase deploy \
                    --only functions \
                    --project pt-admin-4d877 \
                    --region asia-northeast1 \
                    --non-interactive
                    entrypoint: functions/src/index.handler
                    source: functions
                    build_command: yarn build
                    install_command: yarn install --frozen-lockfile

            # Deploy Hosting
            - name: Deploy Hosting
              env:
                  FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
              run: |
                  firebase deploy \
                    --only hosting \
                    --project pt-admin-4d877 \
                    --non-interactive
